### ISSUE TITLE
Possible parallel events

### ISSUE THREAD

**Issue by radonyizsolt** [Yehzuna/schedule#19]
Hi there!

Is there (or will be) any way to have events overlapping each other?

For example like this:
`periods: [
    ['00:00', '04:00'],
    ['01:00', '02:00'],
    ['03:00', '05:00']
]`

Thank you and thanks for the repo!

**Comment by Yehzuna** [comment]
Hi !
It's not possible for the moment and I didn't plan to add this feature.
(It would require to rewrite a lot of code !)
