### ISSUE TITLE
edit-mode event handler prevents buttons from being clickable

### ISSUE THREAD

**Issue by chrisv-dev** [Yehzuna/schedule#20]
I have a div (position:fixed) that gets shown in the middle of my page sometimes (info/warning message for some sort of things). The problem is that when i use jquery-schedule, I can't click on the buttons inside this div anymore. It seems that this is caused by a click event handler which does not allow my button click event to be fired. (probably the one which handles the 'add a new period on-click').

Any ideas how to solve this issue? I thought about something like. "disable edit mode of schedule --> let my popup(div) appear --> let the user click a button --> enable edit mode". But I don't have any idea how I would be able to disable/enable the edit mode at 'runtime' (after creating the schedule with `$('#myElement').jqs(options)` )

I hope the problem is clear, if not let me know and I will try to provide an example.

**Comment by Yehzuna** [comment]
Hello,
I understood your problem but it should not have any interaction between the plugin events  and other events in the page.
Can you give me an example ?

**Comment by chrisv-dev** [comment]
Sure. Have a look at this example:

https://plnkr.co/edit/A0FImmBSKlrpVh5frf5F?p=preview

**Comment by chrisv-dev** [comment]
In case anyone else is struggling with this issue. I solved this by using css-property 'pointer-events' and set it to none.

So something like this:
```
$('#myElement').jqs(options);

onOpenPopup = function(){
   $('#myElement').css('pointer-events','none');
}

onClosePopup = function(){
   $('#myElement').css('pointer-events','');
}
```
pointer-events property browser-support:
https://caniuse.com/#feat=pointer-events
