### ISSUE TITLE
Unable to use in hour blocks

### ISSUE THREAD

**Issue by Mark97192** [Yehzuna/schedule#7]
Hey this isn't really an issue per say, but more of an feature addition requrest, is it possible that you could add the ability to have different time schedule lengths? Like right now you can only select the half hours, but it could be so you could only select a full hour, or 15 minute intervals?

Let me know what you think.

Regards,

Mark

**Comment by Yehzuna** [comment]
Hi, 
As you can see, I'm working on it :)
